plugins {
	id 'net.fabricmc.fabric-loom' version "${loom_version}"
	id 'maven-publish'
}

version = project.version
group = project.group
base {
	archivesName = project.archives_base_name
}

repositories {
	maven {
		name = 'Nucleoid Releases'
		url = 'https://maven.nucleoid.xyz/releases'
	}
}

loom {
	splitEnvironmentSourceSets()

	mods {
		"thaumcraft_reborn" {
			sourceSet sourceSets.main
			sourceSet sourceSets.client
		}
	}
}

fabricApi {
	configureDataGeneration {
		client = true
		outputDirectory = file("src/main/generated")
	}
	configureTests {
		createSourceSet = true
		modId = "thaumcraft_reborn_gametest"
		enableGameTests = true
		enableClientGameTests = true
		eula = true
	}
}

dependencies {
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	implementation "net.fabricmc:fabric-loader:${project.loader_version}"
	implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"
	implementation "eu.pb4:trinkets:${project.trinkets_version}"
}

processResources {
	def modVersion = project.version
	inputs.property "version", modVersion
	filesMatching("fabric.mod.json") {
		expand "version": modVersion
	}
}

tasks.withType(JavaCompile).configureEach {
	options.release = 25
}

java {
	withSourcesJar()
	sourceCompatibility = JavaVersion.VERSION_25
	targetCompatibility = JavaVersion.VERSION_25
}
